# -*- coding: utf-8 -*-
"""Copy of A.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IIrem8T8tTTpjz-80wXgaswEfU2wXzXQ
"""

#import libraries
import folium
import pandas as pd

#create a map on Pakistan location
punjab_map = folium.Map(location = [31.17,72.7],zoom_start=4.5,tiles='OpenStreetMap')

#import Google Drive and mount the entire drive
from google.colab import drive
drive.mount('/content/drive')

#load the dataset (csv file) into the Pandas dataframe
df = pd.read_csv(('/content/drive/My Drive/covid-pak-data1.csv'))
df

#calculate total number of cases using a loop
t = 0
for c in df['Total Cases']:
  t = int(c)+int(t)

#mark circles on the map and displa the map
for city,lat,long,tc,de,re,ac in zip(list(df['city']),list(df['LATITUDE']),list(df['LONGITUDE']),list(df['Total Cases']),list(df['Deaths']),list(df['Recoveries']),list(df['Active Cases'])):
    folium.CircleMarker(location = [lat,long],
                       radius = (tc/t)*100,
                       color = 'red',
                       fill = False,
                       fill_color = 'blue').add_to(pakistan_map)
    xyz = '<strong>city:  ' + city + '</strong><br>' + 'Total Cases: ' + str(tc) + '<br>' + 'Deaths: '+ str(de) + '<br>' + 'Recoveries: ' + str(re) + '<br>' + 'Active Cases: ' + str(ac)
    iframe = folium.IFrame(xyz, width=200, height=150)
    popupData = folium.Popup(iframe, max_width=500)
    folium.Marker(location = [lat,long], popup=popupData).add_to(pakistan_map)
    

pakistan_map