# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1su0zrxCZiiYnxAhk8gbTTtqHLfjcxFSW
"""

import requests
from bs4 import BeautifulSoup

response = requests.get("https://en.wikipedia.org/wiki/List_of_prime_ministers_of_Pakistan")
root = BeautifulSoup(response.text, 'html5lib')

print(root.prettify())
for link in root.find_all('a'):
  print(link.span)